feeds={
"LaNacion":{
    "UltimasNoticias":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=2",
    "Títulosed.impresa":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=1",
    "Política":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
    "Economía":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272",
    "Deportes":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
    "Sociedad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
    "Opinión":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28",
    "Espectáculos":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120",
    "ElMundo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7",
    "RevistaLANACION":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494",
    "SuplementoEnfoques":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421",
    "SuplementoComercioExterior":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347",
    "SuplementoTecnología":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432",
    "SuplementoTurismo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504",
    "SuplementoAlvolante":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371",
    "SuplementoElCampo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337",
    "SuplementoModayBelleza":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312",
    "SuplementoInmueblesComerciales":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363",
    "SuplementoCountries":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348",
    "SuplementoComunidad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344",
    "adnCultura":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734",
    "TheWallStreetJournalAmericas":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373",
    },
"Clarin":{
    "UltimasNoticias":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=2",
    "Títulosed.impresa":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=1",
    "Política":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
    "Economía":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272",
    "Deportes":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
    "Sociedad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
    "Opinión":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28",
    "Espectáculos":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120",
    "ElMundo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7",
    "RevistaLANACION":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494",
    "SuplementoEnfoques":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421",
    "SuplementoComercioExterior":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347",
    "SuplementoTecnología":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432",
    "SuplementoTurismo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504",
    "SuplementoAlvolante":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371",
    "SuplementoElCampo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337",
    "SuplementoModayBelleza":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312",
    "SuplementoInmueblesComerciales":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363",
    "SuplementoCountries":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348",
    "SuplementoComunidad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344",
    "adnCultura":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734",
    "TheWallStreetJournalAmericas":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373",
    },
"Pagina12":{
    "ElPaís":"https://www.pagina12.com.ar/rss/secciones/el-pais/notas",
    "Economía":"https://www.pagina12.com.ar/rss/secciones/economia/notas",
    "Sociedad":"https://www.pagina12.com.ar/rss/secciones/sociedad/notas",
    "ElMundo":"https://www.pagina12.com.ar/rss/secciones/el-mundo/notas",
    "Deportes":"https://www.pagina12.com.ar/rss/secciones/deportes/notas",
    "Cultura":"https://www.pagina12.com.ar/rss/secciones/cultura/notas",
    "Universidad":"https://www.pagina12.com.ar/rss/secciones/universidad/notas",
    "Ciencia":"https://www.pagina12.com.ar/rss/secciones/ciencia/notas",
    "Psicología":"https://www.pagina12.com.ar/rss/secciones/psicologia/notas",
    "Ajedrez":"https://www.pagina12.com.ar/rss/secciones/ajedrez/notas",
    "LaVentana":"https://www.pagina12.com.ar/rss/secciones/la-ventana/notas",
    "Diálogos":"https://www.pagina12.com.ar/rss/secciones/dialogos/notas",
    "Hoy":"https://www.pagina12.com.ar/rss/secciones/hoy/notas",
    "Plástica":"https://www.pagina12.com.ar/rss/secciones/plastica/notas",
    "CartasdeLectores":"https://www.pagina12.com.ar/rss/secciones/cartas-de-lectores/notas",
    },
"Infobae":"https://www.infobae.com/feeds/rss/",
"AmbitoFinanciero":{
    "Portada":"https://www.ambito.com/rss/pages/ultimas-noticias.xml",
    "Últimasnoticias":"https://www.ambito.com/rss/pages/economia.xml",
    "Economía":"https://www.ambito.com/rss/pages/finanzas.xml",
    "Finanzas":"https://www.ambito.com/rss/pages/negocios.xml",
    "Negocios":"https://www.ambito.com/rss/pages/politica.xml",
    "Política":"https://www.ambito.com/rss/pages/nacional.xml",
    "Nacional":"https://www.ambito.com/rss/pages/mundo.xml",
    "Mundo":"https://www.ambito.com/rss/pages/lifestyle.xml",
    "Lifestyle":"https://www.ambito.com/rss/pages/deportes.xml",
    "Deportes":"https://www.ambito.com/rss/pages/espectaculos.xml",
    "Espectáculos":"https://www.ambito.com/rss/pages/tecnologia.xml",
    "Tecnología":"https://www.ambito.com/rss/pages/autos.xml",
    "Autos":"https://www.ambito.com/rss/pages/edicion-impresa.xml",
    "EdiciónImpresa":"https://www.ambito.com/rss/pages/municipios.xml",
    "Municipios":"https://www.ambito.com/rss/pages/novedades-fiscales.xml",
    "NovedadesFiscales	":"https://www.ambito.com/rss/pages/novedades-fiscales.xml",,
    },
"Perfil":{
    "ÚltimoMomento":"https://www.perfil.com/feed",
    "Política":"https://www.perfil.com/feed/politica",
    "Policía":"https://www.perfil.com/feed/policia",
    "Internacionales":"https://www.perfil.com/feed/internacionales",
    "Economía":"https://www.perfil.com/feed/economia",
    "Deportes":"https://www.perfil.com/feed/deportes",
    "Opinión":"https://www.perfil.com/feed/opinion",
    "Sociedad":"https://www.perfil.com/feed/sociedad",
    "Espectáculos":"https://www.perfil.com/feed/espectaculos",
    "Ciencia":"https://www.perfil.com/feed/ciencia",
    "Salud":"https://www.perfil.com/feed/salud",
    "Tecnología":"https://www.perfil.com/feed/tecnologia",
    },
"Iprofesional":{
    "Economía":"www.iprofesional.com/rss/economia",
    "Finanzas":"www.iprofesional.com/rss/finanzas",
    "Impuestos":"www.iprofesional.com/rss/impuestos",
    "Legales":"www.iprofesional.com/rss/legales",
    "Negocios":"www.iprofesional.com/rss/negocios",
    "Tecnología":"ww.iprofesional.com/rss/tecnologia",
    "Comex":"ww.iprofesional.com/rss/comex",
    "Management":"www.iprofesional.com/rss/management",
    "Marketing":"w.iprofesional.com/rss/marketing",
    "Autos":"ww.iprofesional.com/rss/autos",
    "Vinos&Bodegas":"iprofesional.com/rss/vinos",
    },
"BigBangNews":{
    "Política":"https://www.bigbangnews.com/feed/politica",
    "Actualidad":"https://www.bigbangnews.com/feed/actualidad",
    "Show":"https://www.bigbangnews.com/feed/farandula",
    "Televisión":"https://www.bigbangnews.com/feed/television",
    "Deportes":"https://www.bigbangnews.com/feed/deportes",
    "RecetasdeCocina":"https://www.bigbangnews.com/feed/recetas",
    "Tecnología":"https://www.bigbangnews.com/feed/tecnologia",
    "Tapas":"https://www.bigbangnews.com/feed/tapas",
    "Policiales":"https://www.bigbangnews.com/feed/policiales",
    "Mundo":"https://www.bigbangnews.com/feed/mundo",
    },

"AgenciaTélam":{
    "ÚltimasNoticias":"https://www.telam.com.ar/rss2/ultimasnoticias.xml",
    "Política":"https://www.telam.com.ar/rss2/politica.xml",
    "Economía":"https://www.telam.com.ar/rss2/economia.xml",
    "Sociedad":"https://www.telam.com.ar/rss2/sociedad.xml",
    "Deportes":"https://www.telam.com.ar/rss2/deportes.xml",
    "Policiales":"https://www.telam.com.ar/rss2/policiales.xml",
    "Internacional":"https://www.telam.com.ar/rss2/internacional.xml",
    "Latinoamérica":"https://www.telam.com.ar/rss2/latinoamerica.xml",
    "ConoSur":"https://www.telam.com.ar/rss2/conosur.xml",
    "Provincias":"https://www.telam.com.ar/rss2/provincias.xml",
    "Agropecuario":"https://www.telam.com.ar/rss2/agropecuario.xml",
    "Tecnología":"https://www.telam.com.ar/rss2/tecnologia.xml",
    "Cultura":"https://www.telam.com.ar/rss2/cultura.xml",
    "Espectáculos":"https://www.telam.com.ar/rss2/espectaculos.xml",
    "Turismo":"https://www.telam.com.ar/rss2/turismo.xml",
    "Salud":"https://www.telam.com.ar/rss2/salud.xml",
    "Educación":"https://www.telam.com.ar/rss2/educacion.xml",
    "Redes":"https://www.telam.com.ar/rss2/redes.xml",
    },


















"NoticiasArgentinas":"https://noticiasargentinas.com/",
"A24":"https://aaa24.a24films.com/",
"TN":"https://tn.com.ar/",
"C5N":"https://www.c5n.com/",
"ElTrece":"https://www.eltrecetv.com.ar/",
"AméricaTV":"https://www.americatv.com.ar/",
"NetTV":"https://www.canalnet.tv/",
"TVPública":"https://www.tvpublica.com.ar/",
"RadioNacional":"https://www.radionacional.com.ar/welcome/",
"LaVozdelInterior":"http://archivo.lavoz.com.ar/Rss/",
"LosAndes":"https://www.losandes.com.ar/",
"ElLiberal":"https://www.elliberal.com.ar/",
"ElTerritorio":"https://www.elterritorio.com.ar/rss",
"ElChubut":"https://www.elchubut.com.ar/",
"ElPatagónico":"https://www.elpatagonico.com/",
"TiempoArgentino":"https://www.tiempoar.com.ar/",
"ElSol":"https://www.elsol.com.ar/",
"ElDía":"https://www.eldia.com/",
"ElOnce":"https://www.elonce.com/",
"DiariodeCuyo":"https://www.diariodecuyo.com.ar/",
"ElIntransigente":"https://elintransigente.com/",
"DiarioPanorama":"https://www.facebook.com/diariopanorama/?locale=es_ES",
"LaGaceta":"https://www.lagaceta.com.ar/",
"ElTribunodeSalta":"https://www.eltribuno.com/",
"NuevoDiarioWeb":"https://www.nuevodiarioweb.com.ar/rss",
"ElArgentino":"https://elargentinodiario.com.ar/",
====================
"ElCronistaComercial":"https://www.cronista.com/tema/106880/",
}
