feeds={
"LaNacion":{
"UltimasNoticias":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=2",
"Títulosed.impresa":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=1",
"Política":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
"Economía":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272",
"Deportes":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
"Sociedad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
"Opinión":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28",
"Espectáculos":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120",
"ElMundo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7",
"RevistaLANACION":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494",
"SuplementoEnfoques":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421",
"SuplementoComercioExterior":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347",
"SuplementoTecnología":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432",
"SuplementoTurismo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504",
"SuplementoAlvolante":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371",
"SuplementoElCampo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337",
"SuplementoModayBelleza":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312",
"SuplementoInmueblesComerciales":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363",
"SuplementoCountries":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348",
"SuplementoComunidad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344",
"adnCultura":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734",
"TheWallStreetJournalAmericas":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373",
},
"Clarin":{
"UltimasNoticias":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=2",
"Títulosed.impresa":"http://contenidos.lanacion.com.ar/herramientas/rss/origen=1",
"Política":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30",
"Economía":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272",
"Deportes":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131",
"Sociedad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773",
"Opinión":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28",
"Espectáculos":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120",
"ElMundo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7",
"RevistaLANACION":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494",
"SuplementoEnfoques":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421",
"SuplementoComercioExterior":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347",
"SuplementoTecnología":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432",
"SuplementoTurismo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504",
"SuplementoAlvolante":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371",
"SuplementoElCampo":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337",
"SuplementoModayBelleza":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312",
"SuplementoInmueblesComerciales":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363",
"SuplementoCountries":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348",
"SuplementoComunidad":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344",
"adnCultura":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734",
"TheWallStreetJournalAmericas":"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373",
},
"Pagina12":{
"ElPaís":"https://www.pagina12.com.ar/rss/secciones/el-pais/notas",
"Economía":"https://www.pagina12.com.ar/rss/secciones/economia/notas",
"Sociedad":"https://www.pagina12.com.ar/rss/secciones/sociedad/notas",
"ElMundo":"https://www.pagina12.com.ar/rss/secciones/el-mundo/notas",
"Deportes":"https://www.pagina12.com.ar/rss/secciones/deportes/notas",
"Cultura":"https://www.pagina12.com.ar/rss/secciones/cultura/notas",
"Universidad":"https://www.pagina12.com.ar/rss/secciones/universidad/notas",
"Ciencia":"https://www.pagina12.com.ar/rss/secciones/ciencia/notas",
"Psicología":"https://www.pagina12.com.ar/rss/secciones/psicologia/notas",
"Ajedrez":"https://www.pagina12.com.ar/rss/secciones/ajedrez/notas",
"LaVentana":"https://www.pagina12.com.ar/rss/secciones/la-ventana/notas",
"Diálogos":"https://www.pagina12.com.ar/rss/secciones/dialogos/notas",
"Hoy":"https://www.pagina12.com.ar/rss/secciones/hoy/notas",
"Plástica":"https://www.pagina12.com.ar/rss/secciones/plastica/notas",
"CartasdeLectores":"https://www.pagina12.com.ar/rss/secciones/cartas-de-lectores/notas",
},
"AmbitoFinanciero":{
"Portada":"https://www.ambito.com/rss/pages/ultimas-noticias.xml",
"Últimasnoticias":"https://www.ambito.com/rss/pages/economia.xml",
"Economía":"https://www.ambito.com/rss/pages/finanzas.xml",
"Finanzas":"https://www.ambito.com/rss/pages/negocios.xml",
"Negocios":"https://www.ambito.com/rss/pages/politica.xml",
"Política":"https://www.ambito.com/rss/pages/nacional.xml",
"Nacional":"https://www.ambito.com/rss/pages/mundo.xml",
"Mundo":"https://www.ambito.com/rss/pages/lifestyle.xml",
"Lifestyle":"https://www.ambito.com/rss/pages/deportes.xml",
"Deportes":"https://www.ambito.com/rss/pages/espectaculos.xml",
"Espectáculos":"https://www.ambito.com/rss/pages/tecnologia.xml",
"Tecnología":"https://www.ambito.com/rss/pages/autos.xml",
"Autos":"https://www.ambito.com/rss/pages/edicion-impresa.xml",
"EdiciónImpresa":"https://www.ambito.com/rss/pages/municipios.xml",
"Municipios":"https://www.ambito.com/rss/pages/novedades-fiscales.xml",
"NovedadesFiscales	":"https://www.ambito.com/rss/pages/novedades-fiscales.xml",
},
"Perfil":{
"ÚltimoMomento":"https://www.perfil.com/feed",
"Política":"https://www.perfil.com/feed/politica",
"Policía":"https://www.perfil.com/feed/policia",
"Internacionales":"https://www.perfil.com/feed/internacionales",
"Economía":"https://www.perfil.com/feed/economia",
"Deportes":"https://www.perfil.com/feed/deportes",
"Opinión":"https://www.perfil.com/feed/opinion",
"Sociedad":"https://www.perfil.com/feed/sociedad",
"Espectáculos":"https://www.perfil.com/feed/espectaculos",
"Ciencia":"https://www.perfil.com/feed/ciencia",
"Salud":"https://www.perfil.com/feed/salud",
"Tecnología":"https://www.perfil.com/feed/tecnologia",
},
"Iprofesional":{
"Economía":"www.iprofesional.com/rss/economia",
"Finanzas":"www.iprofesional.com/rss/finanzas",
"Impuestos":"www.iprofesional.com/rss/impuestos",
"Legales":"www.iprofesional.com/rss/legales",
"Negocios":"www.iprofesional.com/rss/negocios",
"Tecnología":"ww.iprofesional.com/rss/tecnologia",
"Comex":"ww.iprofesional.com/rss/comex",
"Management":"www.iprofesional.com/rss/management",
"Marketing":"w.iprofesional.com/rss/marketing",
"Autos":"ww.iprofesional.com/rss/autos",
"Vinos&Bodegas":"iprofesional.com/rss/vinos",
},
"BigBangNews":{
"Política":"https://www.bigbangnews.com/feed/politica",
"Actualidad":"https://www.bigbangnews.com/feed/actualidad",
"Show":"https://www.bigbangnews.com/feed/farandula",
"Televisión":"https://www.bigbangnews.com/feed/television",
"Deportes":"https://www.bigbangnews.com/feed/deportes",
"RecetasdeCocina":"https://www.bigbangnews.com/feed/recetas",
"Tecnología":"https://www.bigbangnews.com/feed/tecnologia",
"Tapas":"https://www.bigbangnews.com/feed/tapas",
"Policiales":"https://www.bigbangnews.com/feed/policiales",
"Mundo":"https://www.bigbangnews.com/feed/mundo",
},

"AgenciaTélam":{
"ÚltimasNoticias":"https://www.telam.com.ar/rss2/ultimasnoticias.xml",
"Política":"https://www.telam.com.ar/rss2/politica.xml",
"Economía":"https://www.telam.com.ar/rss2/economia.xml",
"Sociedad":"https://www.telam.com.ar/rss2/sociedad.xml",
"Deportes":"https://www.telam.com.ar/rss2/deportes.xml",
"Policiales":"https://www.telam.com.ar/rss2/policiales.xml",
"Internacional":"https://www.telam.com.ar/rss2/internacional.xml",
"Latinoamérica":"https://www.telam.com.ar/rss2/latinoamerica.xml",
"ConoSur":"https://www.telam.com.ar/rss2/conosur.xml",
"Provincias":"https://www.telam.com.ar/rss2/provincias.xml",
"Agropecuario":"https://www.telam.com.ar/rss2/agropecuario.xml",
"Tecnología":"https://www.telam.com.ar/rss2/tecnologia.xml",
"Cultura":"https://www.telam.com.ar/rss2/cultura.xml",
"Espectáculos":"https://www.telam.com.ar/rss2/espectaculos.xml",
"Turismo":"https://www.telam.com.ar/rss2/turismo.xml",
"Salud":"https://www.telam.com.ar/rss2/salud.xml",
"Educación":"https://www.telam.com.ar/rss2/educacion.xml",
"Redes":"https://www.telam.com.ar/rss2/redes.xml",
},

"cadena3": {

"Agro " : "http://cadena3.com/rss/Agro.xml",
"Deportes " : "http://cadena3.com/rss/Deportes.xml",
"Espectáculos " : "http://cadena3.com/rss/Espectaculos.xml",
"Gastronomía " : "http://cadena3.com/rss/Gastronomia.xml",
"Hobbies " : "http://cadena3.com/rss/Hobbies.xml",
"Humor " : "http://cadena3.com/rss/Humor.xml",
"Internacionales " : "http://cadena3.com/rss/Internacionales.xml",
"Juegos " : "http://cadena3.com/rss/Juegos.xml",
"Juegos de Azar " : "http://cadena3.com/rss/JuegosdeAzar.xml",
"Marcas y Productos " : "http://cadena3.com/rss/MarcasyProductos.xml",
"Mascotas " : "http://cadena3.com/rss/Mascotas.xml",
"Mitos y Leyendas " : "http://cadena3.com/rss/MitosyLeyendas.xml",
"Música " : "http://cadena3.com/rss/Musica.xml",
"Política y Economía " : "http://cadena3.com/rss/PoliticayEconomia.xml",
"Salud " : "http://cadena3.com/rss/Salud.xml",
"San Valentín " : "http://cadena3.com/rss/SanValentin.xml",
"Sociales del Campo " : "http://cadena3.com/rss/SocialesdelCampo.xml",
"Sociedad " : "http://cadena3.com/rss/Sociedad.xml",
"Tecnología " : "http://cadena3.com/rss/Tecnologia.xml",
"Turismo " : "http://cadena3.com/rss/Turismo.xml",
},

"lapoliticaonline":{
 " Últimas noticias": "http://www.lapoliticaonline.com.ar/files/rss/ultimasnoticias.xml ", 
 " Política": "http://www.lapoliticaonline.com.ar/files/rss/politica.xml",
 " Economía": "http://www.lapoliticaonline.com.ar/files/rss/economia.xml",
 " Ciudad": "http://www.lapoliticaonline.com.ar/files/rss/ciudad.xml",
 " Provincia": "http://www.lapoliticaonline.com.ar/files/rss/provincia.xml ", 
 " Conurbano": "http://www.lapoliticaonline.com.ar/files/rss/conurbano.xml ", 
 " Mendoza": "http://www.lapoliticaonline.com.ar/files/rss/mendoza.xml ", 
 " Santa Fe": "http://www.lapoliticaonline.com.ar/files/rss/santafe.xml ", 
 " Transporte": "http://www.lapoliticaonline.com.ar/files/rss/transporte.xml",
 " Energía": "http://www.lapoliticaonline.com.ar/files/rss/energía.xml ", 
 " Judiciales": "http://www.lapoliticaonline.com.ar/files/rss/judiciales.xml",
 " Campo": "http://www.lapoliticaonline.com.ar/files/rss/campo.xml ", 
 " Entrevista": "http://www.lapoliticaonline.com.ar/files/rss/entrevista.xml",
 " Medios": "http://www.lapoliticaonline.com.ar/files/rss/medios.xml",
 " México": "http://www.lapoliticaonline.com.ar/files/rss/mexico.xml",
},

"todoagro":{
"Todas las noticias":"https://www.todoagro.com.ar/noticias/feed/",
"Agricultura	":" https://www.todoagro.com.ar/categoria/agricultura/feed/ ",
"Ganadería	":" https://www.todoagro.com.ar/categoria/ganaderia/feed/",
"Lechería	":" https://www.todoagro.com.ar/categoria/lecheria/feed/ ", 
"Generales	":" https://www.todoagro.com.ar/categoria/generales/feed/",
"Empresarias	":" https://www.todoagro.com.ar/categoria/empresarias/feed/ ",
"Otras producciones	":" https://www.todoagro.com.ar/categoria/otras-producciones/feed/", 
"Energías renovables	":" https://www.todoagro.com.ar/categoria/energias-renovables/feed/", 
"Todos los eventos	":" https://www.todoagro.com.ar/evento/feed/",
"Capacitaciones	":" https://www.todoagro.com.ar/categoria_evento/capacitaciones/feed/ ",
"Exposiciones	":" https://www.todoagro.com.ar/categoria_evento/exposiciones/feed/ ",
"Jornadas	":" https://www.todoagro.com.ar/categoria_evento/jornadas/feed/ ", 
"Presentaciones	":" https://www.todoagro.com.ar/categoria_evento/presentaciones/feed/ ",
"Remates feria	":" https://www.todoagro.com.ar/categoria_evento/remates-feria/feed/",
 },

"diariocronica":{
"Actualidad ":"https://www.diariocronica.com.ar/rss/actualidad/ ", 
"Tecno/Ocio/Ciencia ":" https://www.diariocronica.com.ar/rss/tecno-ocio-ciencia/",
"Cultura":"https://www.diariocronica.com.ar/rss/cultura/",
"Policiales ":" https://www.diariocronica.com.ar/rss/policiales/",
"Deportes ":" https://www.diariocronica.com.ar/rss/deportes/",
"Sociedad ":" https://www.diariocronica.com.ar/rss/sociedad/",
"Economía ":" https://www.diariocronica.com.ar/rss/economia/",
"Política ":" https://www.diariocronica.com.ar/rss/politica/",
"Columnistas":"https://www.diariocronica.com.ar/rss/columnistas/",
"Energía":"https://www.diariocronica.com.ar/rss/energia/",
"Más":"https://www.diariocronica.com.ar/rss/mas/",
"Opinión":"https://www.diariocronica.com.ar/rss/opinion/",
"Solicitada ":" https://www.diariocronica.com.ar/rss/solicitada/",
"Carta del lector ":"https://www.diariocronica.com.ar/rss/carta-del-lector/ ", 
"Principal":"https://www.diariocronica.com.ar/rss/nota-del-dia/ ", 
"QATAR 2022 ":"https://www.diariocronica.com.ar/rss/mundial-qatar-2022/ ", 
"Últimas noticias ":"https://www.diariocronica.com.ar/rss/noticias/ ", 
},



"ElTerritorio":
{
"Ahora ":" https://www.elterritorio.com.ar/rss/ahora/ ", 
"Policiales  ":"https://www.elterritorio.com.ar/rss/policiales/",
"Misiones " :"https://www.elterritorio.com.ar/rss/misiones/ ",  
"Deportes " :"https://www.elterritorio.com.ar/rss/deportes/",
"Actualidad" :"https://www.elterritorio.com.ar/rss/actualidad/ ", 
"La Región " :"https://www.elterritorio.com.ar/rss/la-region/  ", 
"País y Mund " :"https://www.elterritorio.com.ar/rss/pais-y-mundo/ ", 
"Coronavirus " :"https://www.elterritorio.com.ar/rss/coronavirus/  ", 
"Tecno/Ocio " :"https://www.elterritorio.com.ar/rss/tecno-ocio/",
"Vida & Estilo " :"https://www.elterritorio.com.ar/rss/vida-estilo/ ",  
"Tecnología" :"https://www.elterritorio.com.ar/rss/tecnologia/ ", 
"Cultura  " :"https://www.elterritorio.com.ar/rss/cultura/ ",  
"Territorio Fun" :"https://www.elterritorio.com.ar/rss/territorio-fun/ ", 
"Los Cuentos  " :"https://www.elterritorio.com.ar/rss/los-cuentos/ ",  
"Espectáculos & Farándula " :"https://www.elterritorio.com.ar/rss/espectaculos-farandula/ ", 
"Viajes & Turismo " :"https://www.elterritorio.com.ar/rss/viajes-turismo/ ", 
"Fiesta del Inmigrante " :"https://www.elterritorio.com.ar/rss/fiesta-del-inmigrante/  ", 
"Infografías  " :"https://www.elterritorio.com.ar/rss/infografias/ ",  
"TerritorioTV " :"https://www.elterritorio.com.ar/rss/territorio-tv/  ", 
"MetaData " :"https://www.elterritorio.com.ar/rss/metadata/",
"Archivo Criminal " :"https://www.elterritorio.com.ar/rss/archivo-criminal/",
"Conciencia" :"https://www.elterritorio.com.ar/rss/conciencia/ ", 
"Fúnebres " :"https://www.elterritorio.com.ar/rss/funebres/",
"Clasificados " :"https://www.elterritorio.com.ar/rss/clasificados/",
"Radio " :"https://www.elterritorio.com.ar/rss/radio/  ", 
"Diario" :"https://www.elterritorio.com.ar/rss/diario/ ", 
"Edición de hoy  " :"https://www.elterritorio.com.ar/rss/edicion-de-hoy/  ", 
"Club El Territorio  " :"https://www.elterritorio.com.ar/rss/club-el-territorio/  ", 
"Edición Electrónica Flip Page " :"https://www.elterritorio.com.ar/rss/edicion-electronica-flip-page/",
"Edición Impresa  " :"https://www.elterritorio.com.ar/rss/edicion-impresa/ ", 
"Deportes " :"https://www.elterritorio.com.ar/rss/edicion-impresa-deportes/ ",  
"Opinión  " :"https://www.elterritorio.com.ar/rss/edicion-impresa-opinion/ ", 
"Carta de lectores " :"https://www.elterritorio.com.ar/rss/edicion-impresa-carta-de-lectores/",
"Misiones y la region " :"https://www.elterritorio.com.ar/rss/edicion-impresa-misiones-y-la-region/ ",  
"Política " :"https://www.elterritorio.com.ar/rss/edicion-impresa-politica/ ",  
"Economía" :"https://www.elterritorio.com.ar/rss/edicion-impresa-economia/  ", 
"Foja Cero  " :"https://www.elterritorio.com.ar/rss/edicion-impresa-foja-cero/ ", 
"La gente" :"https://www.elterritorio.com.ar/rss/edicion-impresa-la-gente/  ", 
"Alfredo Poenitz " :"https://www.elterritorio.com.ar/rss/edicion-impresa-alfredo-poenitz/",
"Agenda " :"https://www.elterritorio.com.ar/rss/edicion-impresa-agenda/ ",  
"Lectores" :"https://www.elterritorio.com.ar/rss/edicion-impresa-lectores/  ", 
"Marcha de los días " :"https://www.elterritorio.com.ar/rss/edicion-impresa-marca-de-los-dias/  ", 
"Editorial " :"https://www.elterritorio.com.ar/rss/edicion-impresa-editorial/  ", 
"Gonzalo Peltzer" :"https://www.elterritorio.com.ar/rss/edicion-impresa-gonzalo-peltzer/ ",  
"Comerciales" :"https://www.elterritorio.com.ar/rss/edicion-impresa-comerciales/ ",  
"Sociedad  " :"https://www.elterritorio.com.ar/rss/edicion-impresa-sociedad/",
"Turismo" :"https://www.elterritorio.com.ar/rss/edicion-impresa-turismo/ ",  
"El País y El Mundo " :"https://www.elterritorio.com.ar/rss/edicion-impresa-el-pais-y-el-mundo/ ", 
"Informe de Domingo " :"https://www.elterritorio.com.ar/rss/edicion-impresa-informe-de-domingo/ ", 
"Misionero del año " :"https://www.elterritorio.com.ar/rss/misionero/  ", 
"Elecciones " :"https://www.elterritorio.com.ar/rss/elecciones/ ", 
"Últimas noticias  " :"https://www.elterritorio.com.ar/rss/noticias/",
},

"NuevoDiarioWeb":
 {
"Política ":"https://www.nuevodiarioweb.com.ar/rss/politica/  ",  
"La provincia":"https://www.nuevodiarioweb.com.ar/rss/la-provincia/ ", 
"Policiales  ":"https://www.nuevodiarioweb.com.ar/rss/policiales/",
"Deportes ":"https://www.nuevodiarioweb.com.ar/rss/deportes/  ",  
"Espectáculos":"https://www.nuevodiarioweb.com.ar/rss/espectaculos/ ", 
"El País  ":"https://www.nuevodiarioweb.com.ar/rss/el-pais/",  
"El Mundo ":"https://www.nuevodiarioweb.com.ar/rss/el-mundo/  ",  
"Especiales  ":"https://www.nuevodiarioweb.com.ar/rss/especiales/", 
"Opinión  ":"https://www.nuevodiarioweb.com.ar/rss/opinion/", 
"Últimas noticias  ":"https://www.nuevodiarioweb.com.ar/rss/noticias/  ",
},



}
